/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustomGrid: typeof import('./../src/components/custom-grid.vue')['default']
    CustomGrid2: typeof import('./../src/components/custom-grid2.vue')['default']
    CustomGridParam: typeof import('./../src/components/custom-grid-param.vue')['default']
    LongshortHedgingGrid: typeof import('./../src/components/longshort-hedging-grid.vue')['default']
    LongshortHedgingGridParam: typeof import('./../src/components/longshort-hedging-grid-param.vue')['default']
    NutAvatar: typeof import('@nutui/nutui')['Avatar']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutCellGroup: typeof import('@nutui/nutui')['CellGroup']
    NutCheckbox: typeof import('@nutui/nutui')['Checkbox']
    NutCol: typeof import('@nutui/nutui')['Col']
    NutDatePicker: typeof import('@nutui/nutui')['DatePicker']
    NutDivider: typeof import('@nutui/nutui')['Divider']
    NutForm: typeof import('@nutui/nutui')['Form']
    NutFormItem: typeof import('@nutui/nutui')['FormItem']
    NutGrid: typeof import('@nutui/nutui')['Grid']
    NutGridItem: typeof import('@nutui/nutui')['GridItem']
    NutInfiniteLoading: typeof import('@nutui/nutui')['InfiniteLoading']
    NutInput: typeof import('@nutui/nutui')['Input']
    NutMenu: typeof import('@nutui/nutui')['Menu']
    NutMenuItem: typeof import('@nutui/nutui')['MenuItem']
    NutNoticebar: typeof import('@nutui/nutui')['Noticebar']
    NutPicker: typeof import('@nutui/nutui')['Picker']
    NutPopup: typeof import('@nutui/nutui')['Popup']
    NutRadio: typeof import('@nutui/nutui')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui')['RadioGroup']
    NutRow: typeof import('@nutui/nutui')['Row']
    NutSearchbar: typeof import('@nutui/nutui')['Searchbar']
    NutSwiper: typeof import('@nutui/nutui')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui')['SwiperItem']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    NutTable: typeof import('@nutui/nutui')['Table']
    NutTabPane: typeof import('@nutui/nutui')['TabPane']
    NutTabs: typeof import('@nutui/nutui')['Tabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleGrid: typeof import('./../src/components/simple-grid.vue')['default']
    SimpleGridParam: typeof import('./../src/components/simple-grid-param.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanNavBar: typeof import('vant/es')['NavBar']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
  }
}
